hostname: "0.0.0.0"
listen_port: 3000
apis_path: "config/apis"
sources_path: "config/sources"
middleware_path: ""
redis_connection_string: "@@REDIS"
use_dashboard_configs: false
enable_control_api: false
log_level: "info"
